/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __GTKHTML_EDITOR_MARSHAL_MARSHAL_H__
#define __GTKHTML_EDITOR_MARSHAL_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:STRING,POINTER (../../../components/editor/gtkhtml-editor-marshal.list:1) */
extern
void gtkhtml_editor_marshal_VOID__STRING_POINTER (GClosure     *closure,
                                                  GValue       *return_value,
                                                  guint         n_param_values,
                                                  const GValue *param_values,
                                                  gpointer      invocation_hint,
                                                  gpointer      marshal_data);

/* STRING:STRING (../../../components/editor/gtkhtml-editor-marshal.list:2) */
extern
void gtkhtml_editor_marshal_STRING__STRING (GClosure     *closure,
                                            GValue       *return_value,
                                            guint         n_param_values,
                                            const GValue *param_values,
                                            gpointer      invocation_hint,
                                            gpointer      marshal_data);


G_END_DECLS

#endif /* __GTKHTML_EDITOR_MARSHAL_MARSHAL_H__ */
